POST {{HEROKU_URL}}/api/auth/register
Content-Type: application/json

{
  "email": "sergey.mikheev@waveaccess.ru",
  "password": "123login123"
}

###
POST {{HEROKU_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "sergey.mikheev@waveaccess.ru",
  "password": "123login123"
}


###
# Authorized request
GET {{HEROKU_URL}}/api/profile/11
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiYXV0aDAiLCJlbWFpbCI6IlNlcmdleSJ9.M9nx62vIQLdTQyqwllWm0QtBf7exaSz0Pk7VV3g1gP4
###
# Not - Authorized request
GET {{HEROKU_URL}}/api/profile/11
Content-Type: application/json
