POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "Sergey",
  "password": "123login123"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "Sergey",
  "password": "123login123"
}


###
# Authorized request
GET http://localhost:8080/api/profile/11
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsImlzcyI6ImF1dGgwIiwiZW1haWwiOiJTZXJnZXkifQ.TordZk2FProm5MtVds96T406HObGXQVmlid52U2l6D0
###
# Not - Authorized request
GET http://localhost:8080/api/profile/11
Content-Type: application/json
